site_name: IT-Security Docs
# fix 404 error
site_url: https://janfuhrer.github.io/it-security-docs/

nav:
  - 'Index': 'themes/000 Index.md'
  - 'Applied Cryptography 1':
    - 'Index': 'themes/100 AC1 MOC.md'
    - 'Intro': 'themes/101 AC1 TOC - Intro.md'
    - 'Security & Cryptography': 'themes/102 AC1 TOC - Security & Cryptography.md'
    - 'Randomness': 'themes/103 AC1 TOC - Randomness.md'
    - 'Private Key Encryption': 'themes/104 AC1 TOC - Private Key Encryption.md'
    - 'Random Oracle & Applications': 'themes/105 AC1 TOC - Random Oracle & Applications.md'
    - 'AEAD': 'themes/106 AC1 TOC - AEAD.md'
    - 'Secure Channels': 'themes/107 AC1 TOC - Secure Channels.md'
    - 'Blockchain': 'themes/108 AC1 TOC - Blockchain.md'
    - 'Secret Sharing': 'themes/109 AC1 TOC - Secret sharing.md'
  - 'Applied Cryptography 2':
    - 'Index': 'themes/200 AC2 MOC.md'
    - 'Intro': 'themes/201 AC2 TOC - Intro Public Key Encryption.md'
    - 'Modular Arithmetic and Group Theory': 'themes/202 AC2 TOC - Modular Arithmetic and Group Theory.md'
    - 'Number-Theoretic Algorithms': 'themes/203 AC2 TOC - Number-Theoretic Algorithms and Hardness Assumptions.md'
    - 'RSA and ElGamal Encryption': 'themes/204 AC2 TOC - RSA and ElGamal Encryption.md'
    - 'Digital Signatures': 'themes/205 AC2 TOC - Digital Signatures.md'
    - 'Elliptic curves': 'themes/206 AC2 TOC - Elliptic curves.md'
    - 'X.509': 'themes/207 AC2 TOC - X.509.md'
    - 'Centralized PKI': 'themes/208 AC2 TOC - Centralized public-key infrastructures.md'
    - 'Secure Messaging And Channels': 'themes/209 AC2 TOC - Secure messaging and channels.md'
    - 'Anonymity': 'themes/210 AC2 TOC - Anonymity.md'
    - 'DPKI': 'themes/211 AC2 TOC - DPKI.md'
    - 'GNU Taler': 'themes/212 AC2 TOC - GNU Taler.md'
  - 'Modern Cryptography':
    - 'Index': 'themes/300 Modern Cryptography MOC.md'
    - 'Introduction and Classical Cryptography':
      - 'Introduction': 'themes/Introduction to Modern Cryptography.md'
      - 'Perfectly Secret Encryption': 'themes/Perfectly Secret Encryption.md'
      - 'OneTimePad': 'themes/OneTimePad.md'
      - 'Shannons Theorem': 'themes/Shannons Theorem.md'
    - 'Private-Key (Symmetric) Cryptography':
      - 'Computational Security': 'themes/Computational Security.md'
      - 'EAV-Security': 'themes/EAV-Security.md'
      - 'CPA-Security': 'themes/CPA-Security.md'
      - 'Stream Cipher': 'themes/Stream Cipher.md'
      - 'Block Cipher': 'themes/Block Cipher.md'
      - 'Message Authentication Codes': 'themes/MAC.md'
      - 'Cryptographic MACs': 'themes/Cryptographic MACs.md'
      - 'Authenticated Encryption': 'themes/Authenticated Encryption.md'
      - 'CCA-Security': 'themes/CCA-Security.md'
      - 'Hash Functions': 'themes/Hash Functions.md'
      - 'Random-Oracle Model': 'themes/Random-Oracle Model.md'
      - 'Additional Applications of Hash Functions': 'themes/Additional Applications of Hash Functions.md'
      - 'Cryptographic Hash Functions': 'themes/Cryptographic Hash Functions.md'
      - 'Hash-and-Mac': 'themes/Hash-and-Mac.md'

theme:
  name: 'material'
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    # enable instant loading (XHR) -> won't work well with latex math
    #- navigation.instant
    - navigation.top
    - search.highlight
    - navigation.indexes
    - navigation.tabs

  palette:
  # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: purple
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  # Dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep purple
    accent: purple
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/janfuhrer/it-security-docs
